In [1]:
import numpy as np

In [2]:
a=np.array([20,40,60,80])
a

array([20, 40, 60, 80])

In [3]:
b=np.arange(4)
b

array([0, 1, 2, 3])

In [5]:
c=a+b
c

array([20, 41, 62, 83])

In [6]:
a**2

array([ 400, 1600, 3600, 6400], dtype=int32)

In [7]:
a<50

array([ True,  True, False, False])

In [8]:
a+=10
a

array([30, 50, 70, 90])

In [11]:
x=np.random.random(12)
x

array([0.67416236, 0.0354874 , 0.69099806, 0.40596752, 0.3998668 ,
       0.90715654, 0.60856769, 0.14738774, 0.0869634 , 0.16242158,
       0.27995733, 0.26837325])

In [12]:
x.max()

0.9071565444668944

In [13]:
x.min()

0.035487395565713564

In [17]:
x.sum()

4.667309673355477

In [19]:
b=np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
b.sum(axis=0)

array([15, 18, 21, 24, 27])

In [23]:
b.sum(axis=1)

array([10, 35, 60])

In [24]:
b.max(axis=1)

array([ 4,  9, 14])

In [27]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [28]:
k=np.random.random(10)
k

array([0.76909939, 0.58254649, 0.4187749 , 0.83606076, 0.08937706,
       0.02642805, 0.96299856, 0.19279356, 0.288027  , 0.03024068])

In [29]:
k.mean()

0.41963464439034726

In [30]:
np.median(k)

0.3534009460168125

In [31]:
np.std(k)

0.3318747166002383

In [32]:
np.var(k)

0.11014082751848848

In [33]:
kopya=k.copy()
kopya

array([0.76909939, 0.58254649, 0.4187749 , 0.83606076, 0.08937706,
       0.02642805, 0.96299856, 0.19279356, 0.288027  , 0.03024068])

In [34]:
şehir=np.array(['ankara','istanbul','bursa','ankara','izmir','bursa','izmir'])
np.unique(şehir)

array(['ankara', 'bursa', 'istanbul', 'izmir'], dtype='<U8')