In [1]:
import numpy as np

In [4]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a[3]

3

In [7]:
a[3:6]
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a[4]=1000
a

array([   0,    1,    2,    3, 1000,    5,    6,    7,    8,    9])

In [12]:
for i in a:
    print(i*2)

0
2
4
6
2000
10
12
14
16
18


In [13]:
y=np.random.random(16)
y

array([0.56509085, 0.11502588, 0.78836486, 0.9342789 , 0.55585443,
       0.39491856, 0.09009002, 0.01456131, 0.60514706, 0.04085848,
       0.50011374, 0.43171973, 0.7581108 , 0.70835198, 0.56711756,
       0.52922572])

In [15]:
y=y.reshape(4,4)
y

array([[0.56509085, 0.11502588, 0.78836486, 0.9342789 ],
       [0.55585443, 0.39491856, 0.09009002, 0.01456131],
       [0.60514706, 0.04085848, 0.50011374, 0.43171973],
       [0.7581108 , 0.70835198, 0.56711756, 0.52922572]])

In [16]:
y.ravel()

array([0.56509085, 0.11502588, 0.78836486, 0.9342789 , 0.55585443,
       0.39491856, 0.09009002, 0.01456131, 0.60514706, 0.04085848,
       0.50011374, 0.43171973, 0.7581108 , 0.70835198, 0.56711756,
       0.52922572])

In [17]:
y[0:2,1]

array([0.11502588, 0.39491856])

In [18]:
y[:,3]

array([0.9342789 , 0.01456131, 0.43171973, 0.52922572])

In [19]:
for satır in y:
    print(satır)

[0.56509085 0.11502588 0.78836486 0.9342789 ]
[0.55585443 0.39491856 0.09009002 0.01456131]
[0.60514706 0.04085848 0.50011374 0.43171973]
[0.7581108  0.70835198 0.56711756 0.52922572]


In [20]:
for satır in y.flat:
    print(satır)

0.5650908510527393
0.11502587949416132
0.7883648636020552
0.9342789024522118
0.5558544253246368
0.3949185580978758
0.09009001524247617
0.014561308236299642
0.6051470555442827
0.04085848111627022
0.5001137424477587
0.43171972585511253
0.7581107978551613
0.7083519780794206
0.5671175646935619
0.5292257205782513


In [21]:
for satır in np.ndenumerate(y):
    print(satır)

((0, 0), 0.5650908510527393)
((0, 1), 0.11502587949416132)
((0, 2), 0.7883648636020552)
((0, 3), 0.9342789024522118)
((1, 0), 0.5558544253246368)
((1, 1), 0.3949185580978758)
((1, 2), 0.09009001524247617)
((1, 3), 0.014561308236299642)
((2, 0), 0.6051470555442827)
((2, 1), 0.04085848111627022)
((2, 2), 0.5001137424477587)
((2, 3), 0.43171972585511253)
((3, 0), 0.7581107978551613)
((3, 1), 0.7083519780794206)
((3, 2), 0.5671175646935619)
((3, 3), 0.5292257205782513)


In [22]:
a=np.array([2,3])
b=np.array([5,6])

In [23]:
np.hstack([a,b])

array([2, 3, 5, 6])

In [24]:
np.vstack([a,b])

array([[2, 3],
       [5, 6]])

In [25]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
np.concatenate([a,b],axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
np.concatenate([a,b.T],axis=1)

array([[1, 2, 5],
       [3, 4, 6]])