In [5]:
import numpy as np

In [6]:
x = np.array([1,2,3,4]) 

In [7]:
type(x)

numpy.ndarray

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.ones([2,4])*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [17]:
n= np.arange(10,50,5)
n

array([10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
ondalık = np.arange(0,2,0.2)
ondalık

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [21]:
lin = np.linspace(0,4,12)
lin

array([0.        , 0.36363636, 0.72727273, 1.09090909, 1.45454545,
       1.81818182, 2.18181818, 2.54545455, 2.90909091, 3.27272727,
       3.63636364, 4.        ])

In [22]:
rast= np.random.rand(3,4)
rast

array([[0.07853347, 0.68648298, 0.96465237, 0.81128969],
       [0.01286225, 0.08615227, 0.47027243, 0.20547159],
       [0.15593356, 0.03114803, 0.52558112, 0.16141525]])

In [30]:
n= np.random.randn(2,5)*5
n

array([[-5.78991299, 11.33250452, -3.20581193, -2.96476607, -3.39189172],
       [ 6.59810128,  7.21668632,  1.58483274,  2.33829962, -4.72436841]])

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.random.randint(1,50,15)

array([37, 27,  4, 44, 21, 31, 26,  6,  2, 45,  4, 11, 29, 20, 18])

In [34]:
y=np.arange(24)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [35]:
y.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [36]:
y.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [38]:
y.max()

23

In [40]:
y.min()

0

In [41]:
y.argmax()

23

In [42]:
y.argmin()

0

In [44]:
a=np.arange(50)
a.shape=2,-1,5
a.shape

(2, 5, 5)

In [45]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])